force-app/main/default/objects/Payment_Gateway_Config__mdt/Payment_Gateway_Config__mdt.object-meta.xml
<CustomObject>
    <label>Payment Gateway Config</label>
    <pluralLabel>Payment Gateway Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Payment_Gateway_Config__mdt/fields/Auth_Overriding_Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Auth_Overriding_Apex_Class__c</fullName>
    <inlineHelpText>Name of the Apex class that extends RazorpayAuth and overrides the getNamedCredential() method to return the named credential used for authentication.
By default, the getNamedCredential() method in the RazorpayAuth class returns the value from
Payment_Gateway_Config__mdt.getInstance(&apos;Razorpay_Config&apos;).Named_Credential__c.</inlineHelpText>
    <label>Auth Overriding Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/helper/RazorpayAuthRetrieverHelper.cls
public class RazorpayAuthRetrieverHelper {
    public static String getNamedCredential() {
        System.debug('Entering');
        String authOverrideClass = Payment_Gateway_Config__mdt.getInstance('Razorpay_Config').Auth_Overriding_Apex_Class__c;
        System.debug('authOverrideClass ' + authOverrideClass);
        if (authOverrideClass != NULL && !String.isEmpty(authOverrideClass)) {
            Type t = Type.forName(authOverrideClass);

            if (t == null) {
                throw new RazorpayException('Invalid Apex class name: ' + authOverrideClass);
            }

            // Check if the class extends RazorpayAuth
            if (!RazorpayAuth.class.isAssignableFrom(t)) {
                throw new RazorpayException('The class ' + authOverrideClass + ' must extend RazorpayAuth.');
            }

            RazorpayAuth auth = (RazorpayAuth) t.newInstance();
            return auth.getNamedCredential();

        } else {
            return new RazorpayAuth().getNamedCredential();
        }
    }
}