force-app/main/default/objects/Payment_Endpoint__mdt/Payment_Endpoint__mdt.object-meta.xml
<CustomObject>
    <label>Payment Endpoint</label>
    <pluralLabel>Payment Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/Payment_Endpoint__mdt/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <label>Endpoint URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Endpoint__mdt/fields/Response_Entity_Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Response_Entity_Apex_Class__c</fullName>
    <inlineHelpText>Apex entity class name that extends RazorpayBaseEntity, which is also the return type of the Service Class.</inlineHelpText>
    <label>Response Entity Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Endpoint__mdt/fields/REST_Method__c.field-meta.xml
<CustomField>
    <fullName>REST_Method__c</fullName>
    <label>REST Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DELETE</fullName>
                <default>true</default>
                <label>DELETE</label>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Endpoint__mdt/fields/Success_Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Success_Response_Code__c</fullName>
    <inlineHelpText>Eg: 200,201,202,204</inlineHelpText>
    <label>Success Response Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/helper/RazorpayPostRequestHelper.cls
public with sharing class RazorpayPostRequestHelper {
    public static RazorpayBaseEntity execute(String metadataDeveloperName, Map<String, String> replacer, Map<String, Object> body){
        Payment_Endpoint__mdt endpointDetails = Payment_Endpoint__mdt.getInstance(metadataDeveloperName);
        
        if(endpointDetails == NULL) throw new RazorpayException('No custom metadata record available in Payment_Endpoint__mdt with developer name as ' + metadataDeveloperName);
        
        RazorpayRequestBuilder request = new RazorpayRequestBuilder();
        
        String requestBody = RazorpayRequestBodyTransformHelper.transform(body);

        HttpResponse response = request.setEndpoint(endpointDetails.Endpoint_URL__c, replacer)
                                                                     .setMethod(endpointDetails.REST_Method__c)
                                                                     .setBody(requestBody)
                                                                     .send();

        if(request.validate(response, endpointDetails.Success_Response_Code__c)){
            return RazorpayResponseToEntityTransformHelper.transform(response, endpointDetails.Response_Entity_Apex_Class__c);
        }

        return null;
    }
}